services:

  database:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "${PORT_POSTGRES}:${PORT_POSTGRES}" # Optional: expose for debugging.
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      COMPOSE_HTTP_TIMEOUT: ${COMPOSE_HTTP_TIMEOUT}

  backend:
    build:
      context: ./src/back-nestjs
      args:
        PORT: ${PORT_BACKEND}
        PORT_WEBSOCKET: ${PORT_WEBSOCKET}
    volumes:
      - ./src/back-nestjs:/app
      - nestjs_modules:/app/node_modules
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    environment:
      PORT: ${PORT_BACKEND}
      PORT_WEBSOCKET: ${PORT_WEBSOCKET}
    ports:
      - "${PORT_WEBSOCKET}:${PORT_WEBSOCKET}"
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    expose:
      - "${PORT_BACKEND}"
    networks:
      - internal

  frontend:
    build:
      context: ./src/front-vite
      args:
        PORT: ${PORT_FRONTEND}
    volumes:
      - ./src/front-vite:/app
      - react_modules:/app/node_modules
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      PORT: ${PORT_FRONTEND}
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    expose:
      - "${PORT_FRONTEND}"
    networks:
      - internal

volumes:
  pgdata:
  react_modules:
  nestjs_modules:

networks:
  internal:
    driver: bridge
